Async download app
novikkatarina/CsharpEducation pull request #10
Opened 2023-08-25 18:59 UTC by novikkatarina

Приложение для асинхронной загрузки файлов

2023-08-25 19:27 UTC, Dezodemius requested changes

2023-08-25 19:27 UTC, Dezodemius commented on AsyncDownloadApp/DownloadSave.cs
> +  /// <summary>
Поправь доки и форматирование

2023-08-25 19:27 UTC, Dezodemius commented on AsyncDownloadApp/DownloadSave.cs
> +      Console.WriteLine("При загрузке возникла ошибка");
Какая ошибка? Как понять?

2023-08-25 19:27 UTC, Dezodemius commented on AsyncDownloadApp/Program.cs
> +var url1 = "https://youtu.be/GSItB6R7V2g";
кринж

2023-08-25 19:27 UTC, Dezodemius commented on EntityRepository/ConsoleApp1/ConsoleApp1/Program.cs
> +  static Task Main(string[] args)
оно тут не надо

2023-08-25 19:27 UTC, Dezodemius commented on _editorconfig
> +root = true
этот файл тож не нужон

2023-08-25 19:27 UTC, Dezodemius commented on AsyncDownloadApp/Program.cs
> +var task2 = downloadSave.AsyncDownloadSave(url2, path2);
Так-то работает, но нужно, чтоб не пользователь сам задачи отправлял. Он должен только указывать на ссылку, которую хочет скачать. Нужен механизм, который бы делал это за пользователя

2023-08-27 08:55 UTC, novikkatarina commented on AsyncDownloadApp/Program.cs
> +var task2 = downloadSave.AsyncDownloadSave(url2, path2);
Да, абсолютная глупость, случайно осталось в прошлом коммите это только. Не знаю как по человечески написать тестирование, чтобы видно было, что вместе выполняются оба скачивания, пользователь с такой скоростью не может ввести оба url. это был вариант для проверки, как сделать удобоваримо можно? Может две ссылки сразу ему дать ввести.. или тест написать, чтобы показать что второе скачивание начлось позже, чем первое закачалось?

2023-08-27 09:24 UTC, novikkatarina commented on AsyncDownloadApp/Program.cs
> +var task2 = downloadSave.AsyncDownloadSave(url2, path2);
поняла как сделать

2023-08-27 09:28 UTC, novikkatarina commented on AsyncDownloadApp/Program.cs
> +var url1 = "https://youtu.be/GSItB6R7V2g";
а я скажу - вкусовщина. 3 млн людей не могут ошибаться

2023-08-27 09:39 UTC, novikkatarina commented on EntityRepository/ConsoleApp1/ConsoleApp1/Program.cs
> +  static Task Main(string[] args)
После создании ветки сносить все кроме текущего проекта?

2023-08-28 07:51 UTC, Dezodemius commented on EntityRepository/ConsoleApp1/ConsoleApp1/Program.cs
> +  static Task Main(string[] args)
ну ты когда ветку создаёшь, то там делаешь задание. Там лишнего и не должно быть, если так делать

2023-08-28 07:51 UTC, Dezodemius approved these changes

2023-08-28 07:54 UTC, merged