TicTacToe
novikkatarina/CsharpEducation pull request #3
Opened 2023-07-12 11:51 UTC by novikkatarina

- Console
- GUI

2023-07-19 05:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.Console/Logic.cs
> +                System.Console.WriteLine($"{player}, your turn. Choose your position");
используй `using System;`

2023-07-19 05:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.Console/Logic.cs
>      public class Logic
Здесь и везде нужно оформить по соглашению по кодированию. Доки написать, пустые строки вставить, модификаторы везде прописать

2023-07-19 05:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.GUI/Board.cs
> +    public class Board
А класс дописан?

2023-07-19 05:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.Console/VersusComputer.cs
>              Thread.Sleep(500);
Типо, он думает так?

2023-07-19 05:58 UTC, Dezodemius requested changes
Исправь пока это. Потом ещё гляну

2023-07-23 10:04 UTC, novikkatarina commented on Solution1/TicTacToe/TicTacToe.GUI/Board.cs
> +    public class Board
Удалила класс, не нужен

2023-07-23 10:04 UTC, novikkatarina commented on Solution1/TicTacToe/TicTacToe.Console/VersusComputer.cs
>              Thread.Sleep(500);
Да, имитирует.

2023-07-23 10:05 UTC, novikkatarina commented
Исправила @Dezodemius

2023-07-25 11:48 UTC, Dezodemius requested changes

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.GUI/TicTacToe.GUI.sln
> +﻿
А зачем новые решения? Должно быть одно глобальное решение и несколько проектов

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Logic.cs
> +public class Logic
Logic непонятное название для класса. Непонятно, что внутри-то ожидать. Нужно что-то более понятное. Что-то типа TicTacToeGame. Или просто  TicTacToe. Либо TicTacToeRunner

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Board.cs
> +public class Board
Дока в классе нужна

2023-07-25 11:48 UTC, Dezodemius commented on PhonebookSQL/PhonebookSQL.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
А вот это всё решение нужно вообще?

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Multiplayer.cs
> +  private Board board; // null
Зачем этот коммент?

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Multiplayer.cs
> +  {
Конструктор должен быть в конце класса. Посмотри соглашение по кодированию. Там в разделе про регионы есть порядок. Собсно, регионы тоже добавить нужно везде, где это нужно

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Multiplayer.cs
> +    board = new Board(3);
3 лучше вынести в константу класса

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Multiplayer.cs
> +  /// Запускает режим игры с другим игроком.
Дока не соответствует названию

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Multiplayer.cs
> +      Logic.Turn("X", board.Array, out int _, board.GetSize(), out int _,
Крестик нужно в константу вынести

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/VersusComputer.cs
> +public class VersusComputer
Вообще говоря, класс Multiplayer и VersusComputer работают в одном поле. Называться тоже должны соответствующе. В идеале, создать интерфейс IGamingStrategy какой-нибудь. И два этих класса будут его реализовывать. Ну и называться подобным образом

2023-07-25 11:48 UTC, Dezodemius commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/VersusComputer.cs
> +    const string computer = "X";
в константу класса нужно. В других методах у тебя тоже есть крестики. Но не стоит делать одинаковые по смыслу и значению константы выносить  в каждом из классов. Предлагаю создать enum

2023-07-27 16:42 UTC, novikkatarina commented on Solution1/TicTacToe/TicTacToe.ConsoleApp/Logic.cs
> +public class Logic
В данном случае вся логика игры в этом классе, включая расчеты ячеек, дистанций, вероятность ничьей, выигрыша и тд. В связи с этим думаю *логика* в названии должно быть. Оставила TicTacToeLogic

2023-07-28 14:11 UTC, novikkatarina commented
Все исправила @Dezodemius

2023-07-28 17:06 UTC, Dezodemius approved these changes

2023-07-29 12:27 UTC, merged