Phonebook
novikkatarina/CsharpEducation pull request #4
Opened 2023-07-29 19:58 UTC by novikkatarina

2023-07-30 11:08 UTC, Dezodemius requested changes

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +/// Создает телефонную книгу, класс синглтон, позволяет создать только один экземпляр.
Лучше описать его не так подробно. В доке стоит писать общие вещи. В данном случае лучше подошло бы что-то типа 
`Телефонный справочник`

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  private static MyPhonebook myPhonebook;
`Экземпляр класса` достаточно будет в доке

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  readonly string path =
Модификатор доступа. Вообще, норм, но посмотри такую штуку как Path.Combine

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  private static MyPhonebook myPhonebook;
лучше назвать `instance`

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public static MyPhonebook Instance()
Имя нужно аналогично полю дать. В таком случае мы будем их считать связанными. Соответственно, доку нужно оставить только у свойства, а у поля убрать
Ну в доке лучше `Экземпляр класса`

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Имя региона не по соглашению. В презентации про соглашение было описано какие и как должны называться регионы

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public List<Subscriber> List { set; get; }
Лучше же `Subscribers`

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +      Console.WriteLine(item.ToString()));
Вроде как, здесь не нужно писать ToString. Он итак вызовется внутри WriteLine

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +    List = ReadAll();
А для чего каждый раз загружать весь список из файла? Почему это нельзя один раз сделать

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +    int index = List.FindIndex(s => s.Name == subscriber.Name);
А почему не через просто Find, или какой-то другой способ? Странно выглядит

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  /// <returns></returns>
А чё дока не дописана?

2023-07-30 11:08 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +    int index = List.FindIndex(s => s.Name == name);
Посмотри на метод Contains либо Any

2023-07-31 17:45 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public static MyPhonebook Instance()
Изменить название Instance  согласно полю(?), единственное поле это instance в этом классе, либо не хватает какого то поля? Или назвать MyPhonebook? Но метод с таким названием это только конструктор..В данном случае не понятным осталось какое свойство и поле? Не ясно к сожалению, где исправить нужно

2023-07-31 17:59 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Вижу, что зря регион создан, насчет имени - не нашла в соглашении ничего насчет имен(только если точку в конце не ставить)

2023-07-31 18:25 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +      Console.WriteLine(item.ToString()));
Да, точно, я не знала что cw всегда применяет tostring у любого объекта..

2023-07-31 18:32 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +    List = ReadAll();
Лишнее, косяк

2023-07-31 18:48 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +    int index = List.FindIndex(s => s.Name == subscriber.Name);
Казалось уместным, неудачный выбор, исправила.

2023-07-31 18:56 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +    int index = List.FindIndex(s => s.Name == subscriber.Name);
Просто идея была найти есть или нет такой, вроде нет разницы каким методом, там дальше еще firstordefault применялся

2023-08-01 14:51 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Видимо, надо явнее прописать. Там есть слайд про регионы. И есть список членов, которые нужно помещать в один регион. Так вот этот список и показывает как эти регионы называть

2023-08-01 14:59 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Так и называть - методы, константы, поля?

2023-08-01 16:21 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
И не нашла куда классы внутри классов деть

2023-08-01 16:43 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Для классов нет регионов. А так да. Вот как на слайде написано так и пиши

2023-08-01 16:46 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  #region Вывод в консоль
Ааа, вложенные типы это

2023-08-01 17:00 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +    int index = List.FindIndex(s => s.Name == name);
Нашла уместным использовать contains только для create, почему бы и не искать индекс? и сразу по нему к пользователю доступ. Поменяла на Find

2023-08-01 17:04 UTC, novikkatarina commented
Чудокот залит

2023-08-02 05:34 UTC, Dezodemius approved these changes

2023-08-02 05:34 UTC, Dezodemius commented on Phonebook/Phonebook/Message.cs
> +  public const string CreateSub = "Абонент уже существует";
Это ты чётко придумала, мне нравится. Ещё бы доки к каждой строке и отступы, то вообще отпад

2023-08-02 05:34 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public class SubscriberEventArgs
Надо регионы пустой строкой отделять

2023-08-02 05:34 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +    Path.Combine(
нееее, немного не так. В целом, не критично это, но Path.Combine сам поставит `/` между строками, которые ты ему передашь. В линуксе и в маке это `/ `, в винде `\`.
Это работает примерно так
`Path.Combine("Users", "user", "Katarina", ....)`

Ну и у меня же на компе нет пользователя Katarina, как мне быть в этом случае?

2023-08-02 05:34 UTC, Dezodemius commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public static MyPhonebook Instance()
Ты сделала всё правильно

2023-08-02 07:47 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +    Path.Combine(
Даже изучение документации не помогло в прошлый раз, у них там ошибка, по крайней мере в версии для мака. Вымучила еле еле, не уверена, что это будет работать, но вроде должно.

2023-08-02 07:47 UTC, novikkatarina commented on Phonebook/Phonebook/Message.cs
> +  public const string CreateSub = "Абонент уже существует";
Благодарю, приятно, единственное решение, за которое не стыдно.

2023-08-02 07:56 UTC, novikkatarina commented on Phonebook/Phonebook/MyPhonebook.cs
> +  public class SubscriberEventArgs
Ошипка, забыла Эдитор запустить =/. Перед регионом тоже? тут же внутри метода

2023-08-02 08:01 UTC, merged