Practic6 i nterface
novikkatarina/CsharpEducation pull request #6
Opened 2023-08-18 11:45 UTC by novikkatarina

Практика 6. Интерфейсы.

2023-08-23 16:49 UTC, Dezodemius requested changes

2023-08-23 16:49 UTC, Dezodemius commented on Practic6Interface/Practic6/Task1/ListStorage<T>.cs
> +      Console.WriteLine("Индекс больше допустимого.");
ну будто бы исключение нужно кинуть

2023-08-23 16:49 UTC, Dezodemius commented on Practic6Interface/Practic6/Task1/ListStorage<T>.cs
> +    throw new NotImplementedException();
так и надо? Это ж не реализация

2023-08-23 16:49 UTC, Dezodemius commented on Practic6Interface/Practic6/Task1/Program.cs
> +list.Add(4);
ну и обход по циклу foreach бы проверить как работает IEnumerable

2023-08-24 10:55 UTC, novikkatarina commented on Practic6Interface/Practic6/Task1/Program.cs
> +list.Add(4);
в задании не было использовать iEnumerable так то. Я исправила

2023-08-25 19:29 UTC, Dezodemius approved these changes

2023-08-27 09:43 UTC, merged